# Data Types and Structures

### 1. What are data structure, and why are they important?
 - Data structures are a way to organising data so that it can be more efficiently depending on the situation. Main four data structures are Lists, Sets, Tuple and Dict.
 - Data structures are crucial in Python because they provide a structures way to organize and store data, allowing for effecient access, manipulation, and processing, ultimately leading to cleaner, more readable code imporved performance when dealing with large datasets or complex operations within your program.


 ### 2. Explain the difference between mutable and immutable data types with examples.
  - Mutable data types can be modify after creation. Lists, Sets, and Dict are mutable data types.

    list = [1, 3, 5, 2]
    list.append(6)  adding and element to the list
    print(list)  this will print ; [1, 3, 5, 2, 6]

  - Immutable data types does not allow to modify after creation. Int, float, string and tuple are immutable data types.

    tuple = (1, 3, 2)
    tuple.append(5)  this will show an error


### 3. What are the main differences between lists and tuples in Python?
  - Lists and tuples are both fundamental sequence data types in Python. Lists are mutable, their elements can be changed after creation while tuples are immutable means you cannot change after creation once only you can delete the tuple. Tuples are generally more memory-efficient and faster than lists due to their immutability. Lists are defined using square brackets [], while tuples are defined using parantheses ().Lists have more built-in methods available for manipulating their contents like append(), insert(), remove().


  list = [1, 3, 2]
  list.append(4)
  print(list)
  output: [1, 3, 2, 4]

  tuple = (1, 3, 2)
  tuple.append(4) this will raise an error


### 4. Describe how dictionaries store data.
  - Dictionaries store data as key-value pairs, where each unique key is associated with a corresponding value allowing for efficient retrieval of data specifying the key.

  obj = {"name": "Abhinay", "age": 22, "city": "Noida"}
  print(obj["name"])  output : Abhinay
  print(obj["age"]) output : 22


### 5. Why might you use set instead of list in Python?
  - One of the main advantages of using sets in Python is that they are highly optimized for membership tests. sets do membership tests a lot more efficiently than lists. Sets cannot have duplicate value every value must be unique. Cant change the elements of sets just add and remove.



### 6. What is a string in Python. and how is it different from list.
  - A string is a sequence of characters enclosed in either single quotes(") or double quotes(""). strings are used for representing textual data. Strings are immutable.

  str = "Abhinay"  this is string
  print(str)
  - if you wanna change any character in string it will raise an error
  str[0] = "t" this will raise error.


### 7. How do tuples ensure data integrity in python?
  - Tuples are immutable to ensure that their contents remain constant throughout their lifecycle, guaranteeing data integrity and reliability.


### 8. What is a hash table, and how does it relate to dictionaries in Python?
  - Hash table in Python is a data sturcture which stores data by using a pair of values and keys. Each data value is allocated an exclusive key that is created by using the hash fucntions.
  - Dictionaries are implemented using hash tables. When a key-value pair is added to a dictionary, Pythong calculates the hash value of the key and uses it to determine the location to store the value. When retrieving a value, Python again calculates the hash value of the key and uses it to quickly locate the corresponding value. This implementation makes dictionaries very efficient for lookups, insertions, and deletions.



### 9. Can lists contain different data types in Python?
  - Yes, in Python lists can contain different data types as like int, string, float, tuple etc.
  list = [1, "Abhinay", 1.2, (1, 4)]



### 10. Explain why strings are immutable in Python?
  - Strings are immutable because strings does not allow to make any type of modification in Python. We can verfy by trying to update a part of the string which will led us to an error.

  Can not reassign
  str = "Abhinay"
  print type(str)
  str[1] = "v"

  output : TypeError: 'str' object does not support item assignment.



### 11. What advantages do dictionaries offer over lists for certain tasks?
  - Dictionaries make code much easier to read if we need to generate key:value pairs.We can look up a certain value in a dictionary very quickly. Instead, with a list, we would have to read the list before we hit the required element. This difference grows drastically if we increase the number of elements.



### 12.  Describe a scenario where using a tuple would be preferable ober a list.
  - If you need an immutable collection where the elements won't change after creation. Here is some examples that you don't want to change by any user in your project: value of pi(ùûπ), speed of light, Gravitational constant, etc.



### 13. How do sets handle duplicate values in Python?
  - Sets in Python are designed to store only unique elements. When an attempt is made to add a duplicate value to set, Python automatically discards the duplicate, ensuring that the set contains only distinct elements. This behavior stems from the mathematical definition of a set, which does not allow for repetition of elements.

  set1 = {1, 1, 2, 3, 4, 4, 5, 6}
  print(set1)
  output: {1, 2, 3, 4, 5, 6}



### 14. How does the "in" keyword work differently for lists and dictionaries?
  - When using the "in" keyword in Python, it checks if an element is present in a list based on its position (index), while in a dictionary, it checks if a specific key exists within the key-value pairs. In a list you are checking if a value is "in" the sequence, whereas in a dictionary, you are checking if a "key" is "in" the collection.


  my_list = ["apple", "banana", "orange"]

  print("apple" in my_list)  # Output: True (because "apple" is in the list)


  my_dict = {"fruit": "apple", "color": "red"}

  print("apple" in my_dict)  # Output: True (because "apple" is a key in the dictionary)


### 15.  Can you modify the elements of a tuple? Explain why or why not?
  - No, you cannot modify the elements of a tuple in Python because tuples are immutable. This means that once a tuple is created, its elements cannot be changed, added, or removed.
  1. Tuples are similar to lists but unlike lists, tuples are immutable.
  2. Tuples are more memory efficient compared to lists.
  3. If you attempt to alter a tuple element, you will recieve a TypeError error.
  4. You can concatenate 2 or more tuples to form a new tuple.
  5. You can convert the tuple into a list, change the list, and convert the list back into a tuple.

  t = ('a', 'b', 'c', 'd', 'e')
t[0] = 'A'
print(t) #TypeError: object doesn't support item assignment [7]


### 16.  What is a nested dictionary, and give an example of its use case?
  - A nested dictionary is a dictionary that is stored within another dictionary. It's a way to organize data into multiple layers.

  Example:-

  An Organized chat can be represented using a nested dictionary, where departments are keys and the value are dictionaries of employees in each department.

  Use Cases:-

  Employee record: Organize employees by department, with each employees details in a nested dictionary.
  
  Inventory systems: Track product categories , subcategories, and individual product details.

  JSON data: Nested dictionaries map to the structure of json data, making them useful for working with APIs and web services.



### 17.  Describe the time complexity of accessing elements in a dictionary.
  - The time complexity of accessing an element in a dictionary is O(1) on average, which means it takes constant time regardless of the dictionary's size. However, the worst-case time complexity can be O(n) if there are many collisions.



### 18.  In what situations are lists preferred over dictionaries?
  - Lists are preferred over dictionaries when the order of elements is crucial, you need to perform operations on sequential data, or when you want to easily add or remove elements from a collection in a specific order, as lists maintain the order of their elements while dictionaries prioritize fast lookups using keys.



### 19.  Why are dictionaries considered unordered, and how does that affect data retrieval?
  - Dictionaries are considered unordered because they don't maintain the order in which items are added. This is because dictionaries are optimized for fast lookups based on keys.



### 20. Explain the difference between a list and a dictionary in terms of data retrieval.
  - List:-

  Items in a list have a specific order, and you can retrieve items uisng their index positions. You can access elements by their position in the list, starting from 0.
  Lists are best when you need an ordered collection of items that you access by their index.

  list = [19, 43, 23, 52]
  print(list[2])
  output: 23

  Dictionaries:-

  Items in a dictionary are not in any particular order.
  You retrieve items using keys, which are unique identifires for the items in the dictionary.
  Dictionaries are ideal when you need to store pairs of keys and values, and you want to access the items using keys.

  dict = {"apple": 1, "banana": 2, "papaya": 3}
  print(dict["banana"])
  output: 2

## Practical questions.

In [ ]:
# 1. Write a code to create a string with your name and print it

name = "Abhinay"
print(name)

Abhinay

In [ ]:
# 2. Write a code to find the length of the string "Hello World"

str = "Hello World"
print(len(str))

11

In [ ]:
# 3. Write a code to slice the first 3 characters from the string "Python Programming"

str = "Python Programming"
print(str[:3])

Pyt

In [ ]:
# 4. Write a code to convert the string "hello" to uppercase.

str = "hello"
print(str.upper())

HELLO

In [ ]:
# 5. Write a code to replace the word "apple" with "orange" in the string "I like apple"

str = "I like apple"
print(str.replace("apple", "orange"))

I like orange

In [ ]:
# 6.  Write a code to create a list with numbers 1 to 5 and print it.

list = [1, 2, 3, 4, 5]
print(list)

[1, 2, 3, 4, 5]

In [ ]:
# 7. Write a code to append the number 10 to the list [1, 2, 3, 4]

list = [1, 2, 3, 4]
list.append(10)
print(list)

[1, 2, 3, 4, 10]

In [ ]:
# 8. Write a code to remove the number 3 from the list [1, 2, 3, 4, 5]

list = [1, 2, 3, 4, 5]
list.remove(3)
print(list)

[1, 2, 4, 5]

In [ ]:
# 9. Write a code to access the second element in the list ['a', 'b', 'c', 'd']

list = ['a', 'b', 'c', 'd']
print(list[1])

b

In [ ]:
# 10. Write a code to reverse the list [10, 20, 30, 40, 50].

list = [10, 20, 30, 40, 50]
print(list[::-1])

[50, 40, 30, 20, 10]

In [ ]:
# 11.  Write a code to create a tuple with the elements 100, 200, 300 and print it.

tuple = (100, 200, 300)
print(tuple)

(100, 200, 300)

In [ ]:
# 12.  Write a code to access the second-to-last element of the tuple ('red', 'green', 'blue', 'yellow')

tuple = ('red', 'green', 'blue', 'yellow')
print(tuple[-2])

blue

In [ ]:
# 13. Write a code to find the minimum number in the tuple (10, 20, 5, 15).

tuple = (10, 20, 5, 15)
print(min(tuple))

5

In [ ]:
# 14. Write a code to find the index of the element "cat" in the tuple ('dog', 'cat', 'rabbit').

tuple = ('dog', 'cat', 'rabbit')
print(tuple.index("cat"))

1

In [ ]:
# 15.  Write a code to create a tuple containing three different fruits and check if "kiwi" is in it

tuple = ("apple", "banana", "orange")
print("kiwi" in tuple)

False

In [ ]:
# 16. . Write a code to create a set with the elements 'a', 'b', 'c' and print it.

set = {'a', 'b', 'c'}
print(set)

{'b', 'a', 'c'}

In [ ]:
# 17.  Write a code to clear all elements from the set {1, 2, 3, 4, 5}.

set = {1, 2, 3, 4, 5}
set.clear()
print(set)

set()

In [ ]:
# 18.  Write a code to remove the element 4 from the set {1, 2, 3, 4}

set = {1, 2, 3, 4}
set.remove(4)
print(set)

{1, 2, 3}

In [ ]:
# 19.  Write a code to find the union of two sets {1, 2, 3} and {3, 4, 5}

set = {1, 2, 3}
set1 = {3, 4, 5}
#print(set.union(set1))
print(set | set1)

{1, 2, 3, 4, 5}

In [ ]:
# 20.  Write a code to find the intersection of two sets {1, 2, 3} and {2, 3, 4}.

set = {1, 2, 3}
set1 = {2, 3, 4}
print(set & set1)

{2, 3}

In [ ]:
# 21.  Write a code to create a dictionary with the keys "name", "age", and "city", and print it.

dict = {"name": "Abhinay", "age": 22, "city": "Noida"}
print(dict)

{'name': 'Abhinay', 'age': 22, 'city': 'Noida'}

In [ ]:
# 22.  Write a code to add a new key-value pair "country": "USA" to the dictionary {'name': 'John', 'age': 25}.

dict = {'name': 'John', 'age': 25}
dict["country"] = "USA"
print(dict)

{'name': 'John', 'age': 25, 'country': 'USA'}

In [ ]:
# 23. Write a code to access the value associated with the key "name" in the dictionary {'name': 'Alice', 'age': 30}.

dict = {'name': 'Alice', 'age': 30}
print(dict["name"])

Alice

In [ ]:
# 24.  Write a code to remove the key "age" from the dictionary {'name': 'Bob', 'age': 22, 'city': 'New York'}.

dict = {'name': 'Bob', 'age': 22, 'city': 'New York'}
dict.pop("age")
print(dict)

{'name': 'Bob', 'city': 'New York'}

In [ ]:
# 25. Write a code to check if the key "city" exists in the dictionary {'name': 'Alice', 'city': 'Paris'}.

dict = {'name': 'Alice', 'city': 'Paris'}
print("city" in dict)

True

In [ ]:
# 26. Write a code to create a list, a tuple, and a dictionary, and print them all.

list = [1, 3, 5]
print(list)

tuple = (1, 3, 5)
print(tuple)

dict = {"name": "Abhinay", "age": 22, "city": "Noida"}
print(dict)

[1, 3, 5]
(1, 3, 5)
{'name': 'Abhinay', 'age': 22, 'city': 'Noida'}

In [ ]:
# 27.  Write a code to create a list of 5 random numbers between 1 and 100, sort it in ascending order, and print the result. (replaced)

list = [63, 23, 62, 97, 12]
print(sorted(list))

[12, 23, 62, 63, 97]

In [ ]:
# 28. Write a code to create a list with strings and print the element at the third index

list = ["apple", "banana", "orange"]
print(list[2])

orange

In [ ]:
# 29. Write a code to combine two dictionaries into one and print the result.

dict = {"name": "Abhinay", "age": 22, "city": "Noida"}
dict1 = {"country": "India"}
dict.update(dict1)
print(dict)

{'name': 'Abhinay', 'age': 22, 'city': 'Noida', 'country': 'India'}

In [75]:
# 30. Write a code to convert a list of strings into a set.

string_list = ["apple", "banana", "cherry", "apple"]

# Remove any potential variable shadowing
try:
    del set
except NameError:
    pass

try:
    string_set = set(string_list)
    print(string_set)
except TypeError as e:
    print(f"Encountered a TypeError: {e}")

{'cherry', 'apple', 'banana'}